---
- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers

- name: Make sure the unzip/tar packages are present
  ansible.builtin.package:
    name:
      - unzip
      - tar
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  environment: "{{ proxy_env | default({}) }}"
  tags: grafana, grafana_install

- block:
    - name: Install; Start; and Enable Grafana
      ansible.builtin.command: >
        apt-get install -y apt-transport-https software-properties-common wget
        mkdir -p /etc/apt/keyrings/
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
        apt-get update
        apt-get install grafana
        systemctl enable grafana-server
        systemctl start grafana-server
      retries: 10
      delay: 10
  tags: grafana, grafana_install

- name: Wait for port 9090 to become open on the host
  ansible.builtin.wait_for:
    port: 3000
    host: 127.0.0.1
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  tags: grafana, grafana_start
  