---
- name: Make sure handlers are flushed immediately
  ansible.builtin.meta: flush_handlers

- name: Make sure the unzip/tar packages are present
  ansible.builtin.package:
    name:
      - unzip
      - tar
    state: present
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  environment: "{{ proxy_env | default({}) }}"
  tags: prometheus, prometheus_install

- block: # install prometheus package from tar
    - name: Download "prometheus" package
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /
        timeout: 60
        validate_certs: false
      loop:
        - "{{ prometheus_package_tar }}"
      environment: "{{ proxy_env | default({}) }}"

    - name: Extract "prometheus" into /
      ansible.builtin.unarchive:
        src: "/{{ prometheus_package_tar | basename }}"
        dest: /
        extra_opts:
          - --no-same-owner
        remote_src: true

  when:
    - installation_method == "tar"
    - prometheus_package_tar | length > 0
    - not ansible_check_mode
  tags: prometheus, prometheus_install

- name: Generate conf file "/prometheus.yml"
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: /prometheus.yml
  tags: prometheus, prometheus_conf

- name: Generate conf file "/prometheus.service"
  ansible.builtin.template:
    src: templates/prometheus.service.j2
    dest: /prometheus.service
  tags: prometheus, prometheus_conf

- block:
    - name: Enable and Start Prometheus
      ansible.builtin.command: >
        systemctl daemon-reload
        systemctl enable prometheus
        systemctl start prometheus
      retries: 10
      delay: 10
  tags: prometheus, prometheus_conf

- name: Wait for port 9090 to become open on the host
  ansible.builtin.wait_for:
    port: 9090
    host: 127.0.0.1
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  tags: prometheus, prometheus_start
